[mypy]
python_version = 3.12
ignore_missing_imports = True
warn_return_any = False
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = False
show_error_codes = True
exclude = alembic|tests

[mypy-app.agent.schemas]
ignore_errors = True

[mypy-app.services.llm]
ignore_errors = True

[mypy-app.rag.vector_store]
ignore_errors = True
